### ISSUE TITLE
Refactor elasticjob-lite-spring-boot-starter configuration structure

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere-elasticjob#1216]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.
Reducing configuration levels.

Present:
https://github.com/apache/shardingsphere-elasticjob/blob/eb219f788cc25f57245bbeb90d7955877e0c35a8/elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter/src/test/resources/application-elasticjob.yml#L25-L41

Expected:
```yaml
elasticjob:
  tracing:
    type: RDB
  regCenter:
    serverLists: localhost:18181
    namespace: elasticjob-lite-spring-boot-starter
  jobs:
    customTestJob:
      elasticJobClass: org.apache.shardingsphere.elasticjob.lite.spring.boot.job.fixture.job.impl.CustomTestJob
      cron: 0/5 * * * * ?
      shardingTotalCount: 3
    printTestJob:
      elasticJobType: PRINT
      shardingTotalCount: 3
      cron: 0/5 * * * * ?
      props:
        print.content: "test print job"
```
