### ISSUE TITLE
Adapt spring boot starter with job error handler

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1597]

**Comment by TeslaCN** [comment]
I can make it.

**Comment by TeslaCN** [comment]
Now I have designed a new configuration format.

### Before
```yaml
    simpleJob:
      elasticJobClass: org.apache.shardingsphere.elasticjob.lite.example.job.SpringBootSimpleJob
      cron: 0/5 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      props:
        email:
          host: host
          port: 465
          username: username
          password: password
          protocol: smtp
          useSsl: true
          subject: ElasticJob error message
          from: from@xxx.com
          to: to1@xxx.com,to2@xxx.com
          cc: cc@xxx.com
          bcc: bcc@xxx.com
          debug: false
```

### After
```yaml
    simpleJob:
      elasticJobClass: org.apache.shardingsphere.elasticjob.lite.example.job.SpringBootSimpleJob
      cron: 0/5 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      extraConfigurationBeans:
      - beanClass: org.apache.shardingsphere.elasticjob.error.handler.dingtalk.DingtalkConfiguration
        props:
          webhook: my-webhook
          keyword: my-keyword
          secret: my-secret
      - beanClass: org.apache.shardingsphere.elasticjob.error.handler.email.EmailConfiguration
        props:
          host: smtp.myhost
          port: 465
          username: my-username
          password: my-password
          useSsl: true
          from: my@email.com
          to: target@email.com
          debug: true
```
