### ISSUE TITLE
Tracing Module may be unavailable if overwrite is false in 3.0.0-beta

### ISSUE THREAD

**Issue by johnny2002** [apache/shardingsphere-elasticjob#1742]
## Bug Report
I use elasticjob with spring-boot, datasource config correctly, while I cannot get any job trace data and job history data.

### Which version of ElasticJob did you use? 
3.0.0-beta

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite

### Expected behavior
Can see job trance and history in ui console at: http://localhost:8088/#/history-trace

### Actual behavior
Empty table 

### Reason analyze (If you can)
JobScheduler.findTracingConfiguration() returns empty result.

### Steps to reproduce the behavior.
Use the official example,  "elasticjob-example-lite-springboot“, datasource as:
```yaml
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 
```

**Comment by TeslaCN** [comment]
Have you specify the tracing type "RDB"?

**Comment by johnny2002** [comment]
Do you mean this?
```yaml
elasticjob:
  streaming.process: true
  tracing:
    type: RDB
  regCenter:
    serverLists: localhost:2181
    namespace: elasticjob-lite-springboot
    maxRetries: 3
```
