### ISSUE TITLE
error: Invalid config event received

### ISSUE THREAD

**Issue by liujunjia1996** [apache/shardingsphere-elasticjob#1812]
i got this when booting,but my job seem is running ok:
2021-01-19 09:52:21.622 ERROR 11604 --- [ain-EventThread] o.a.c.framework.imps.EnsembleTracker     : Invalid config event received: {server.2=10.176.70.222:2888:3888:participant, server.1=10.176.70.220:2888:3888:participant, server.3=10.176.70.221:2888:3888:participant, version=0}

my zk version: 3.6.2

my application.yml:
```
elasticjob:
  regCenter:
    serverLists: 10.176.70.220:2181,10.176.70.221:2181,10.176.70.222:2181
    namespace: operation-log-elastic-job321312
    base-sleep-time-milliseconds: 2000
    max-sleep-time-milliseconds: 2000
    max-retries: 5
    session-timeout-milliseconds: 2000
    connection-timeout-milliseconds: 2000
  jobs:
    simpleJob:
      elasticJobClass: com.example.demo.OldLogDeleteJob
      cron: 0/12 * * * * ?
      shardingTotalCount: 1
      overwrite: true
```

why i recived this error,is this matter?
