### ISSUE TITLE
文档中说提供自定义的Spring Boot Starter没太明白这个是什么意思

### ISSUE THREAD

**Issue by xdxTao** [apache/shardingsphere-elasticjob#1914]
![image](https://user-images.githubusercontent.com/37034233/123782946-6c9b1280-d908-11eb-9894-b42f795846f3.png)

我引入的pom文件如下
```
<dependency>
    <groupId>org.apache.shardingsphere.elasticjob</groupId>
    <artifactId>elasticjob-lite-core</artifactId>
    <version>3.0.0-RC1</version>
</dependency>
```

配置文件如下

```
elasticjob:
  regCenter:
    serverLists: 127.0.0.1:2181
    namespace: my-job
  jobs:
    simpleJob:
      elasticJobClass: com.elastic.job.MyElasticJob
      cron: 0/1 * * * * ?
      shardingTotalCount: 1
      shardingItemParameters:

```

怎么都无法开启定时任务。  难道说这个Starter是需要我自己去制作一个吗？

ps：使用Java API的方式可以调用成功
