### ISSUE TITLE
elasticjob.tracing.type=RDB does not support configuration specific jobs?

### ISSUE THREAD

**Issue by cjhz** [apache/shardingsphere-elasticjob#1965]
when i use module "elasticjob-lite-spring-boot-starter" and configure elasticjob.tracing.type=RDB  does not support configuration specific jobs? Currently, all global jobs are effective

**Comment by TeslaCN** [comment]
My idea is adding a black-and-white list like the following:
```yaml
elasticjob:
  tracing:
    type: RDB
    includeJobNames: [ job1, job2 ]
    excludeJobNames: [ job0 ]
```
Tracing is enable for all jobs by default.
