### ISSUE TITLE
how to use trace datasource?

### ISSUE THREAD

**Issue by yujun-8848** [apache/shardingsphere-elasticjob#1976]
I want to use com.mysql.cj.jdbc.Driver,dut it not support;
![image](https://user-images.githubusercontent.com/59599368/132478167-654420af-7eff-4cfc-98c8-89730c0d57f6.png)

springboot 2.2.6
elasticjob-lite-spring-boot-starter 3.0.0

**Comment by sunkai-cai** [comment]
you need add JDBC driver JAR to ext-lib. look at this  https://github.com/apache/shardingsphere-elasticjob-ui/blob/master/README.md

**Comment by yujun-8848** [comment]
i see it ,and i have added jar into ext-lib,but why not create  auto table?
or i need to create it by myself.
![image](https://user-images.githubusercontent.com/59599368/132612439-a79168b0-b503-40e1-8ee7-c83a6465c856.png)

**Comment by sunkai-cai** [comment]
maybe you not start the elasticjob ？

**Comment by yujun-8848** [comment]
i have started the elasticjob ,but it doesn't create talbes,if it work well ,database job will create two talbes to trace.
i don't know how to do it?

```
elasticjob:
  tracing:
    type: RDB
  regCenter:
    serverLists: 192.168.102.62:2181
    namespace: elasticjob-demo
    baseSleepTimeMilliseconds: 2000
    maxSleepTimeMilliseconds: 4000
    maxRetries: 3
  jobs:
    firstJob:
      elasticJobClass: com.job.demo.job.FirstJob
      cron: 0/6 * * * * ?
      shardingTotalCount: 5
      enableEventTrace: true
    secondJob:
      elasticJobClass: com.job.demo.job.SecondJob
      cron: 0/5 * * * * ?
      shardingTotalCount: 1
      enableEventTrace: true

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.102.62:3306/job?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: xxx


```
 <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.xiaominfo.swagger</groupId>
            <artifactId>service-user</artifactId>
            <version>1.0</version>
        </dependency>


        
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere.elasticjob</groupId>
            <artifactId>elasticjob-lite-spring-boot-starter</artifactId>
            <version>${elasticjob-lite.version}</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.2.3.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.3.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere.elasticjob</groupId>
            <artifactId>elasticjob-error-handler-dingtalk</artifactId>
            <version>${elasticjob-lite.version}</version>
        </dependency>
    </dependencies>


![image](https://user-images.githubusercontent.com/59599368/132637789-31556052-4d7a-4c25-835d-1261f69c88e6.png)
