### ISSUE TITLE
发现使用elasticjob-lite-spring-boot-starter时,"事件追踪"不起作用

### ISSUE THREAD

**Issue by wjw465150** [apache/shardingsphere-elasticjob#2018]
我在SpringBoot(版本2.4.12)里引入了elasticjob-lite-spring-boot-starter(版本3.0.1),写的Job能正常运行,但是没有"事件追踪".调试发现"TracingConfiguration"也被正常创建了,但是数据库里没有创建相关的表.所以也看不到任何的Job事件!

**Comment by cocodroid** [comment]
Maybe you used it wrong? What kind of data source are you using? show your config

**Comment by wjw465150** [comment]
The configuration file
```yaml
server:
  port: 8889
  servlet:
    context-path: /job

---
spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://127.0.0.1:3306/ElasticJob?useSSL=false&useUnicode=true&characterEncoding=utf-8"
    username: root
    password: 11111111
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      
---
# elasticjob的基本配置
elasticjob:
  tracing:
    type: RDB
  regCenter:
    serverLists: 127.0.0.1:2181
    namespace: ElasticJob
  dump:
    port: 9888

---
# 这里配置需要运行的Job
elasticjob:
  jobs:
    MyElasticJob:
      elasticJobClass: org.wjw.elasticjob.task.MyElasticJob
      cron: 0/30 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      
```

ElasticJobConfig
```java
@Configuration
public class ElasticJobConfig {
  /**
   * 将作业运行的痕迹进行持久化到DB
   *
   * @return
   * @throws TracingConfigurationException 
   */
  @Bean
  public TracingListener RDBTracingListenerConfiguration(DataSource dataSource) throws TracingConfigurationException {
    return new RDBTracingListenerConfiguration().createTracingListener(dataSource);
  }

}

```

MyElasticJob
```java
@Component
public class MyElasticJob implements SimpleJob {
  private final Logger logger = LoggerFactory.getLogger(this.getClass());

  @Override
  public void execute(ShardingContext shardingContext) {
    //打印出任务相关信息，JobParameter用于传递任务的ID
    logger.info("JobName：{}, ShardingTotalCount：{}, JobParameter={}, ShardingItem: {}, ShardingParameter: {}",
        shardingContext.getJobName(),
        shardingContext.getShardingTotalCount(),
        shardingContext.getJobParameter(),
        shardingContext.getShardingItem(),
        shardingContext.getShardingParameter()
        );
  }
}

```

**Comment by cocodroid** [comment]
It's normal for me，Can you support your pom.xml ?

**Comment by wjw465150** [comment]
build.gradle

```groovy
plugins {
  id 'org.springframework.boot' version '2.4.12'
  id 'io.spring.dependency-management' version '1.0.11.RELEASE'
  id 'java'
  id 'war'
}

ext {
  elasticjob = [version : '3.0.1']
}


group = 'org.wjw'
version = '1.0.0'
sourceCompatibility = '1.8'
targetCompatibility = '1.8'
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
[compileJava, compileTestJava]*.options*.compilerArgs << "-parameters" << "-Xlint:deprecation"  //编译参数
[compileJava, compileTestJava]*.options*.deprecation = true

repositories {
  mavenLocal()
  maven { url "https://maven.aliyun.com/nexus/content/groups/public/" }  //优先使用阿里的镜像
  mavenCentral()
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-web'
  providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'

  //集成:elasticjob-lite
  implementation "org.apache.shardingsphere.elasticjob:elasticjob-lite-spring-boot-starter:${elasticjob.version}"
 
  //将作业运行的痕迹进行持久化到DB的时候elasticjob-lite需要
  implementation 'org.springframework.boot:spring-boot-starter-jdbc'
  runtimeOnly 'mysql:mysql-connector-java:5.1.49'
  
  
  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  //@wjw_comment: For Eclipse Run JUnit5
  testImplementation 'org.junit.platform:junit-platform-launcher'
}

test {
  useJUnitPlatform()
}

```

**Comment by cocodroid** [comment]
You can try it. 
Add:
```yml
elasticjob:
  jobs:
    MyElasticJob:
         overwrite: true
```
