### ISSUE TITLE
Application startup failed, start by elasticjob-lite-spring-boot-starter

### ISSUE THREAD

**Issue by junfugao8** [apache/shardingsphere-elasticjob#2057]
### Nearby logs
```
Initializing ExecutorService
spring-cloud-starter-eureka is deprecated as of Spring Cloud Netflix 1.4.0, please migrate to spring-cloud-starter-netflix-eureka
creating Job Bootstrap Beans
Stopping service [Tomcat]
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
Application startup failed
Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@eb21112: startup date [Mon Feb 28 21:32:10 CST 2022]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@23223dd8
Setting initial instance status as: STARTING
Unregistering application promotion-center with eureka with status DOWN
Unregistering JMX-exposed beans on shutdown
```
Only so much log
However, I can start successfully by changing the namespace
I use `elasticjob-lite-spring-boot-starter` to start job
by yml
```
elasticjob:
  reg-center:
    namespace: job-center
  jobs:
    RankingProcess:
      elasticJobClass: com.lq.activity.process.RankingProcess
      cron: 0 0 */1 * * ?
      sharding-total-count: 1
      description: update something
```
Why don't I need to change the namespace to start the program，How can I fix it，And avoid failure to start next time.
