### ISSUE TITLE
For elasticjob-error-handler , can multiple jobs support global configuration

### ISSUE THREAD

**Issue by lvguangzeng** [apache/shardingsphere-elasticjob#2180]
The configuration in the documentation doesn't work properly
<img width="840" alt="image" src="https://user-images.githubusercontent.com/13690075/217421096-0be44217-c261-4302-9663-3d8b722dc455.png">

**current correct configuration**
<img width="406" alt="image" src="https://user-images.githubusercontent.com/13690075/217423577-b54e0504-2b23-4ff5-a64e-7e7d377ae0fa.png">

Can you support the configuration method in the document?
For example, if multiple jobs are configured with WECHAT, the corresponding wechat.webhook needs to be configured only once.

**Comment by cocodroid** [comment]
Can you use this method to solve your problem ?

```
wechatProp : &wechatProp
  wechat:
    webhook: you_webhook
    connectTimeout: 3000
    readTimeout: 5000

xxxJob1: 
  ......
  jobErrorHandlerType: WECHAT
 props: *wechatProp

xxxJob2: 
  ......
  jobErrorHandlerType: WECHAT
 props: *wechatProp
```
