### ISSUE TITLE
When inserting JOB_EXECUTION_LOG, transaction should be committed explicitly accordingly

### ISSUE THREAD

**Issue by ddwolf** [apache/shardingsphere-elasticjob#573]
There could be exception occured in this line: "Lock wait timeout exceeded; try restarting transaction"

https://github.com/elasticjob/elastic-job-lite/blob/b022898ef1b8c984e17efb2a422ee45f6b13e46e/elastic-job-lite-core/src/main/java/io/elasticjob/lite/event/rdb/JobEventRdbStorage.java#L179

The dataSource object could be setup with defaultAutoCommit=false like this:

```yaml
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_IP:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:my_db}
    defaultAutoCommit: false
```

 so if without explicitly commit, there would be transaction exception throwed.
