### ISSUE TITLE
Add spring boot starter

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#970]
It is better to add spring boot starter for ElasticJob.

**Comment by TeslaCN** [comment]
I can make it, please assign to me.

**Comment by 8rV1n** [comment]
Count me in if more volunteers are needed.

**Comment by jiang2015** [comment]
I try to write.

**Comment by TeslaCN** [comment]
I am working on it.

**Comment by yu199195** [comment]
@TeslaCN  you maybe  up speed

**Comment by jiang2015** [comment]
I have done,I want to see the author how to work

**Comment by TeslaCN** [comment]
I have designed some annotations to simplify job definition such as:
```java
@ElasticJob(
        jobBootstrapType = JobBootstrapType.SCHEDULE,
        jobName = "springBootSimpleJob",
        shardingTotalCount = 3,
        shardingItemParameters = "0=Beijing,1=Shanghai,2=Guangzhou",
        cron = "0/10 * * * * ?"
)
@Tracing("tracingConfig1")
@RegistryCenter("zookeeper1")
public class SpringBootSimpleJob implements SimpleJob {

    @Autowired
    private FooRepository fooRepository;

    @Override
    public void execute(ShardingContext shardingContext) {
        System.out.println(String.format("Item: %s | Time: %s | Thread: %s | %s",
                shardingContext.getShardingItem(), new SimpleDateFormat("HH:mm:ss").format(new Date()), Thread.currentThread().getId(), "SIMPLE"));
        List<Foo> data = fooRepository.findTodoData(shardingContext.getShardingParameter(), 10);
        for (Foo each : data) {
            fooRepository.setCompleted(each.getId());
        }
    }
}
```
or
```java
    @Bean
    @ElasticJob(
            jobName = "springBootBeanSimpleJob",
            shardingTotalCount = 3,
            shardingItemParameters = "0=Beijing,1=Shanghai,2=Guangzhou",
            cron = "0/10 * * * * ?",
            jobBootstrapType = JobBootstrapType.SCHEDULE)
    @Tracing("tracingConfig2")
    public SpringBootBeanSimpleJob springBootBeanSimpleJob(FooRepository fooRepository) {
        return new SpringBootBeanSimpleJob(fooRepository);
    }
```

Configuration:
```yaml
elasticjob:
  enabled: true
  registryCenter:
    zookeeper:
      serverLists: 10.105.25.80:2181
      namespace: elasticjob
  tracing:
    type: RDB
spring:
  datasource:
    url: jdbc:h2:mem:job_event_storage
    driver-class-name: org.h2.Driver
    username: sa
    password:
```
No further configuration is required.
